task:
  timeout_in: 115m
  pip_cache:
    folder: ~/.cache/pip
    fingerprint_script: echo $CIRRUS_OS
  matrix:
    - container:
        image: ubuntu:22.04
      install_script:
        - export RUNLEVEL=0
        - apt-get update
        - apt-get install -y curl python3 python3-pip git wget unzip ftp


  script:
    - python3 vercel.json 
    ##- lua all.lua
    #- popd
    #- python3 waf uninstall_clang
    #- python3 waf clean_clang
    ## clang ]
    ## test script
    #- python3 scripts/run_test.py -c gcc -c clang --simple-test
